-- 1. Select all employees whose department location is in Seattle.
SELECT E.*
FROM EMPLOYEES E
    FULL JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    FULL JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
WHERE L.CITY = 'Seattle';

-- 2. Select all countries where employees work as 'Stock Clerk'.
SELECT C.COUNTRY_NAME
FROM COUNTRIES C
    FULL JOIN LOCATIONS L ON C.COUNTRY_ID = L.COUNTRY_ID
    FULL JOIN DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID
    FULL JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
    FULL JOIN JOBS J ON E.JOB_ID = J.JOB_ID
WHERE J.JOB_TITLE = 'Stock Clerk'
GROUP BY C.COUNTRY_NAME;

-- 3. Select all employees from the Europe region with a salary between 9000 and 17000.
SELECT E.*
FROM EMPLOYEES E
    FULL JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    FULL JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
    FULL JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID
    FULL JOIN REGIONS R ON C.REGION_ID = R.REGION_ID
WHERE R.REGION_NAME = 'Europe' AND E.SALARY <= 17000 AND E.SALARY >= 9000;

-- 4. Select all jobs where employees earn more than the minimum salary according to the MIN_SALARY attribute of the JOBS table.
SELECT J.JOB_TITLE
FROM JOBS J
    FULL JOIN EMPLOYEES E ON J.JOB_ID = E.JOB_ID
WHERE E.SALARY > J.MIN_SALARY
GROUP BY J.JOB_TITLE;

-- 5. Select departments where employees work in positions with a maximum salary above 15000.
SELECT D.DEPARTMENT_NAME
FROM DEPARTMENTS D
    FULL JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
    FULL JOIN JOBS J ON E.JOB_ID = J.JOB_ID
WHERE J.MAX_SALARY > 15000
GROUP BY D.DEPARTMENT_NAME;

-- 6. Select all departments and their employees with their salaries.
SELECT CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS EMPLOYEE_NAME,
       D.DEPARTMENT_NAME,
       E.SALARY
FROM DEPARTMENTS D
    FULL JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
    FULL JOIN JOBS J ON E.JOB_ID = J.JOB_ID
ORDER BY D.DEPARTMENT_NAME;

-- 7. Select all employees, their positions, and the countries where they work.
SELECT CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS EMPLOYEE_NAME,
       J.JOB_TITLE,
       C.COUNTRY_NAME
FROM COUNTRIES C
    FULL JOIN LOCATIONS L ON C.COUNTRY_ID = L.COUNTRY_ID
    FULL JOIN DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID
    FULL JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
    FULL JOIN JOBS J ON E.JOB_ID = J.JOB_ID;
